# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'museum_classification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for museum_classification

  target 'museum_classificationTests' do
    inherit! :search_paths
    pod 'TensorFlowLiteSwift'
    # Pods for testing
  end

  target 'museum_classificationUITests' do
    # Pods for testing
  end

end
